// <auto-generated />
namespace CSharp.Course.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SubmissionDateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubmissionDateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201704042107472_SubmissionDateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
